version: "3.8"

services:
    api:
        container_name: 411-api
        build: ./api
        expose:
            - "5000"
        command: python estimationService.py

    nginx:
        container_name: 411-nginx
        build: ./nginx
        ports:
            - "80:80"
        depends_on:
            - api
