# syntax = docker/dockerfile:experimental

FROM python:3.11.6

# make directories
RUN mkdir -p /home/project/app
WORKDIR /home/project/app

# copy and install packages for flask
COPY requirements.txt /home/project/app
RUN pip install --no-cache-dir -r ./requirements.txt

# copy contents from local to the docker container
COPY . /home/project/app
COPY ./lib/ /home/project/app/lib

EXPOSE 5000
